# Generated by Django 4.0.5 on 2022-07-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tovar", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="tovar",
            new_name="tovarn",
        ),
    ]
