# Generated by Django 4.0.5 on 2022-07-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tovar", "0003_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="tovarn",
            name="pages",
            field=models.IntegerField(default=100),
        ),
    ]
