# Generated by Django 4.0.5 on 2022-07-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tovar", "0004_tovarn_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tovarn",
            name="pages",
            field=models.CharField(max_length=255),
        ),
    ]
