# Generated by Django 4.0.5 on 2022-07-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tovar", "0005_alter_tovarn_pages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tovarn",
            old_name="pages",
            new_name="image",
        ),
    ]
