# Generated by Django 4.0.5 on 2022-07-31 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tovar", "0006_rename_pages_tovarn_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tovarn",
            name="image",
        ),
    ]
